### ISSUE TITLE
[ICON REQUEST]: Cypress

### ISSUE THREAD

**Issue by xavierkoo** [devicons/devicon#1842] opened 2023-07-28 08:49 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Cypress is a front end testing tool for web applications.

### Links and sources

https://www.cypress.io/

**Comment by canaleal** [comment] 2023-08-06 02:26
I'm surprised this one hasn't been added yet. I can get a PR up tomorrow afternoon, but iIn case someone else want's to handle this ticket, here are the Cypress Media logos in SVG format:

https://www.cypress.io/press-kit/

**Comment by Snailedlt** [comment] 2023-10-29 13:36
Duplicate of #223

**Closed by Snailedlt** 2023-10-29 13:36 UTC
Labels: request:icon
