### ISSUE TITLE
[ICON REQUEST]: <postman>

### ISSUE THREAD

**Issue by DevBrunoRafael** [devicons/devicon#1353] opened 2022-08-19 23:13 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

ferramenta bastante usada no back-end

### Links and sources

https://www.svgrepo.com/show/354202/postman-icon.svg

**Comment by szmazhr** [comment] 2022-08-20 03:34
duplicate of #933

**Closed** 2022-08-20 17:27 UTC
Labels: request:icon
