### ISSUE TITLE
[ICON REQUEST]:  Tableau

### ISSUE THREAD

**Issue by Laxman-Lakhan** [devicons/devicon#1217] opened 2022-06-16 14:43 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Tableau is a Visualization tool

### Links and sources

https://www.tableau.com

**Comment by Snailedlt** [comment] 2022-10-08 23:32
Duplicate of #1030

**Closed by Snailedlt** 2022-10-08 23:32 UTC
Labels: request:icon
