### ISSUE TITLE
Icon request: VB.NET

### ISSUE THREAD

**Issue by rishaank** [devicons/devicon#1052] opened 2022-02-28 04:20 UTC
### About the icon

(Visual Basic) This is a popular object oriented programming language made by Microsoft and can be found in Visual Studio.

### Links and sources

 This is Microsoft's official article on vb.net but it provides little information. ([https://docs.microsoft.com/en-us/dotnet/visual-basic/](https://docs.microsoft.com/en-us/dotnet/visual-basic/))

There are multiple variations of the logo, this is the one that I thought looked the best ([https://icon-library.com/icon/vb-net-icon-1.html](https://icon-library.com/icon/vb-net-icon-1.html))

Wikipedia's article on VB.net that has more info ([https://en.wikipedia.org/wiki/Visual_Basic_.NET](https://en.wikipedia.org/wiki/Visual_Basic_.NET))

Thank's a lot, this is just a suggestion, I'm just a 11 year old kid who wanted this icon

**Comment by liuxilu** [comment] 2022-04-02 08:59
That reads Microsoft .NET... How about this?
![image](https://user-images.githubusercontent.com/53636947/161374799-0ed96a0e-85b6-49b5-9bb8-d9031f9580ae.png)

**Comment by rishaank** [comment] 2022-10-11 08:31
Sure! But maybe you could try to modernize it? Thanks for the quick
response.

**Comment by Snailedlt** [comment] 2023-10-29 13:28
Duplicate of #910

**Closed by Snailedlt** 2023-10-29 13:28 UTC
Labels: request:icon
