### ISSUE TITLE
Gradients in icons not working all the time when using SVG icons directly

### ISSUE THREAD

**Issue by maltejur** [devicons/devicon#573] opened 2021-04-24 11:41 UTC
Icons with gradients do not work when using more than one and using them as a SVG like described on the website. [Demo](https://codesandbox.io/s/jolly-dust-qcqqk?file=/index.html)

This is beause the icons define gradients with a id, like this:
```html
<defs>
  <linearGradient
    id="a"
    gradientUnits="userSpaceOnUse"
    x1="82.925"
    y1="97.718"
    x2="82.925"
    y2="97.9"
    gradientTransform="translate(0 8.224) scale(.77317)"
  >
    <stop offset="0" stop-color="#F29100"></stop>
    <stop offset="1" stop-color="#EC670F"></stop>
  </linearGradient>
</defs>
```

Because all of the icons starting with the id `a`, using more then one icon with a gradient does not work (at least that's what I think).

Is there any easy solution to this? Should we just give all current gradients a random id and write in the `
CONTRIBUTING.md` that new icons should have to do the same?

**Comment by Thomas-Boi** [comment] 2021-04-25 19:47
Good catch @maltejur.

As a quick fix, unfortunately for now you'll have to change the id of the svg manually.

A more permanent fix on our end would be writing a script that change the id of each svg file to the file name and a random number.  Then, we'll make a new bot the runs this script whenever an svg is submitted and open a PR into the PR branch. 

@amacado do you think this is a breaking change? If so, we'll have to plan this carefully.

**Comment by amacado** [comment] 2021-04-27 14:43
I can verify the bug and it's even worse ;-) I created [this demo](https://codepen.io/amacado/pen/wvgZaNE) to show the issue:
![image](https://user-images.githubusercontent.com/8781699/116258581-5f7d6e00-a775-11eb-89ee-afab7b63a7e3.png)

As you though @maltejur it's caused by the `id`s which are used multiple times across the icons. A solution, as @Thomas-Boi mentioned, would be to prefix/rename all `id`s. Here comes by "and it's even worse": As you can see in my example there are multiple `id`s defined in one svg (a,b,c...) so we'd have to rename all of them and make sure no collisions occur across the project. I think this can be achieved by prefixing all id's with the name of the icon (f.e. gimp-original-wordmark-**_upcounting/random-number_**).

Some research shows that we are not the only ones who'd came up with this problem: https://github.com/airbnb/babel-plugin-inline-react-svg/issues/46

I don't see this as a breaking change as long as we do not change the look of the icons but only the id's. It would only break if someone uses the `id`s as reference for anything (f.e. styling them via css). But I think this is more likely a theoretical break?

**Comment by Thomas-Boi** [comment] 2021-04-27 16:58
Ok that sounds good. I'll start thinking of a script then. I think `filename-counter` should be enough. If needed, we can use `uuid` or its equivalence for python.

**Comment by Panquesito7** [comment] 2021-04-27 17:06
Thank you for your help. For now, what could we use as a temporary fix?

**Comment by amacado** [comment] 2021-04-27 20:59
> Thank you for your help. For now, what could we use as a temporary fix?

Replace the id by hand when you have conflicting id's of svg icons you want to use ;-)

**Comment by Panquesito7** [comment] 2021-04-27 21:04
Sorry for my ignorance, but: what ID do I have to set? 😅

**Comment by amacado** [comment] 2021-04-28 07:59
All `id`s of the `<linearGradient>` tags, see this example:
![image](https://user-images.githubusercontent.com/8781699/116368169-5b4e6080-a808-11eb-912e-f26bcd062c17.png)

**Comment by Panquesito7** [comment] 2021-04-28 17:49
Sorry for not explaining, but I actually meant what value to set it to. I have found those in the SVG, but not sure if I should remove them, change their ID, or what should I do. Thanks for your help. 🙂

**Comment by Thomas-Boi** [comment] 2021-04-28 20:12
You'll need to change them to unique values so it doesn't clash across files

> Sorry for not explaining, but I actually meant what value to set it to. I have found those in the SVG, but not sure if I should remove them, change their ID, or what should I do. Thanks for your help. 🙂

You'll need to change the ids to unique values so it doesn't clash across files. For example, right now file `a.svg` and `b.svg` both has ids of `a`. You'll want to change all reference to that id in `a.svg` to something like `a-a`. For `b.svg`, change the id to something like `b-a`.

This means if you use both svgs in a page, the ids wouldn't clash.

**Comment by Thomas-Boi** [comment] 2021-04-30 23:47
Also, I found out that using the `<img>` tags would not cause the gradient to clash. Perhaps you can use the tag rather than inlining the svg if possible?

Using tags:
![image](https://user-images.githubusercontent.com/43018778/116763818-b97b6f00-a9d3-11eb-82df-775bc03f84be.png)

**Comment by Thomas-Boi** [comment] 2021-05-25 16:08
This is now fixed using our new optimize task via SVGO

**Closed by Thomas-Boi** 2021-05-25 16:08 UTC
Labels: bug, devops
