### ISSUE TITLE
Icon request: Microsoft Visual Basic

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#910] opened 2021-11-12 00:17 UTC
### About the icon

Visual Basic is an object-oriented programming language developed by Microsoft. Using Visual Basic makes it fast and easy to create type-safe .NET apps.

### Links and sources

Info on the language: https://docs.microsoft.com/en-us/dotnet/visual-basic/
Logo (PNG): https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/VB.NET_Logo.svg/512px-VB.NET_Logo.svg.png

### Additional information

Request from the Discord server by [`</MICO>`](https://github.com/DEV-MICO)

**Comment by BenSouchet** [comment] 2022-01-15 14:30
Duplicate of https://github.com/devicons/devicon/issues/184 and https://github.com/devicons/devicon/issues/213
@Thomas-Boi

**Comment by Thomas-Boi** [comment] 2022-01-15 18:28
Thanks @BenSouchet for pointing out the duplicates.

**Comment by canaleal** [comment] 2024-06-15 22:02
Closing as the icon now exists in the master branch.
https://github.com/devicons/devicon/tree/master/icons/visualbasic

**Closed by canaleal** 2024-06-15 22:02 UTC
Labels: request:icon
