### ISSUE TITLE
[ICON REQUEST]: mariaDB

### ISSUE THREAD

**Issue by TomPecs** [devicons/devicon#921] opened 2021-11-25 16:23 UTC
### About the icon

would be nice to have mariaDB icon too :)

### Links and sources

main website: https://mariadb.org
docker website: https://hub.docker.com/_/mariadb

https://raw.githubusercontent.com/docker-library/docs/fe985dcb24154456254e252d1fa4a2b6b656ee80/mariadb/logo.png

**Comment by Snailedlt** [comment] 2021-12-04 02:07
Logos can be found here: https://mariadb.com/about-us/logos/

**Comment by Snailedlt** [comment] 2022-05-05 21:25
# Preview of all SVG logos from their [website](https://mariadb.com/about-us/logos/)

## blue-horizontal
![blue-horizontal](https://mariadb.com/wp-content/uploads/2019/11/mariadb-horizontal-blue.svg)

## black-horizontal
![black-horizontal](https://mariadb.com/wp-content/uploads/2019/11/mariadb-horizontal-black.svg)

## white-horizontal
![white-horizontal](https://mariadb.com/wp-content/uploads/2019/11/mariadb-horizontal-white.svg)

## blue-vertical
![blue-vertical](https://mariadb.com/wp-content/uploads/2019/11/mariadb-logo-vertical_blue.svg)

## black-vertical
![black-vertical](https://mariadb.com/wp-content/uploads/2019/11/vertical-logo_black.svg)

## white-vertical
![white-vertical](https://mariadb.com/wp-content/uploads/2019/11/mariadb-logo-vertical_white.svg)

**Comment by Snailedlt** [comment] 2022-07-26 16:19
@BenSouchet Did you start working on this? If not, I'll assign it to me, and start :)

**Comment by BenSouchet** [comment] 2022-07-26 16:23
@Snailedlt Yes you can, I haven't started this one :)

**Comment by Snailedlt** [comment] 2022-10-27 11:29
Haven't gotten around to this issue yet, so unassigning myself. Hope someone else can take it, since it would be a nice addition :)

**Comment by Snailedlt** [comment] 2023-10-07 11:41
@shaaoni The issue is solved, but not yet published. Hence the `in-develop` label :)
You can see the icons that got added in #1769

**Closed** 2023-10-29 14:48 UTC
Labels: request:icon, good first issue, in-develop
