### ISSUE TITLE
[ICON REQUEST]: Hardhat icon

### ISSUE THREAD

**Issue by knight-95** [devicons/devicon#1355] opened 2022-08-20 04:02 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Hardhat is a popular Ethereum development environment 

### Links and sources

Link to official website : **https://hardhat.org/**
Link to official Documentation : **https://hardhat.org/docs**
Official Logo link : **https://seeklogo.com/vector-logo/426726/hardhat**

**Comment by knight-95** [comment] 2022-08-20 04:05
I would like to work on this issue, kindly assign me for the same

**Comment by Snailedlt** [comment] 2022-10-09 00:05
Duplicate of #957

**Closed by Snailedlt** 2022-10-09 00:05 UTC
Labels: request:icon
