### ISSUE TITLE
JetBrains icons out of date

### ISSUE THREAD

**Issue by MattIPv4** [devicons/devicon#128] opened 2018-06-16 16:00 UTC
All the JetBrains product icons appear to be the versions prior to the modern branding update the occurred. Could these all be updated to the modern branding set that JetBrains uses?

See https://www.jetbrains.com/company/press/index.html#product-logos for all current product icons.

**Comment by iamclaytonray** [comment] 2018-12-12 13:12
If you could, please file your issue (and any new issues) to the new repo/fork [here](https://github.com/iamclaytonray/devicon). Thanks!

**Comment by iamclaytonray** [comment] 2018-12-12 14:12
@MattIPv4 - Thanks for opening an issue on my fork. I didn't think Konpa would make me a collaborator so I didn't ask but I ended up one anyways! We're going to stick with this repo so we don't have to overhaul to another repo, migrating issues, PRs, and so on. Please bear with me as I try to get everything situated (reviewing PRs, issues, and so on) before we really start rolling things out and getting releases out! Thank you so much for your contributions!

**Comment by MattIPv4** [comment] 2019-02-21 22:47
@iamclaytonray any update regarding all of this?

**Comment by tupaschoal** [comment] 2021-07-02 03:16
For the sake of documenting, here are the JetBrains app icons currently on devicons which would require update:
- IntelliJ
- PhpStorm
- PyCharm
- RubyMine
- WebStorm

**Comment by amino19** [comment] 2021-10-31 16:59
@Panquesito7: It seems like, we have to close this issue, get resolved in #711. WDYT?

**Comment by MattIPv4** [comment] 2021-10-31 17:02
The updated JetBrains icon has a missing `s` in the logo, and that's the only one that has been updated, not all the other product icons.

**Comment by amino19** [comment] 2021-10-31 17:11
> The updated JetBrains icon has a missing `s` in the logo, and that's the only one that has been updated, not all the other product icons.

Thanks for your response, Will sure fix that! :slightly_smiling_face:

**Comment by amino19** [comment] 2021-11-01 08:58
Original having `s` in it:
![jetbrains-original](https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jetbrains/jetbrains-original.svg)

seems like `JetBrains-plain` missed it:-
![jetbrains-plain](https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jetbrains/jetbrains-plain.svg)

**Comment by amino19** [comment] 2021-11-02 20:57
@Panquesito7: Do you mind assigning me this issue?

**Comment by Snailedlt** [comment] 2021-12-04 02:01
Would be nice if you could also use "jetbrains" as a tag for all jetbrains products. If I understand the use of aliases correctly, it would make it much easier to search for on the https://devicon.dev/ website ;)

**Comment by Panquesito7** [comment] 2021-12-05 15:24
> Would be nice if you could also use "jetbrains" as a tag for all jetbrains products. If I understand the use of aliases correctly, it would make it much easier to search for on the https://devicon.dev/ website ;)

The `aliases` field is to make an alias for the icon's versions. For example:

```json
      "aliases": [
          {
              "base": "original",
              "alias": "plain"
          },
          {
              "base": "original-wordmark",
              "alias": "plain-wordmark"
          }
      ]
```

**Closed** 2021-12-22 17:41 UTC
Labels: request:icon

**Comment by Snailedlt** [comment] 2022-05-06 07:41
This issue should not have been closed imo, since only the jetbrains logo got updated, and not all of the other icons specified in the issue.

But there is now a new issue that's basically a duplicate of this one ( #1125 ), along with a PR in the works #1182 , so this being closed now is fine. 

Would be great to have some input on the PR other than just mine though :)
