### ISSUE TITLE
[ICON REQUEST]: <ROS>

### ISSUE THREAD

**Issue by bardpedersen** [devicons/devicon#1504] opened 2022-11-08 17:15 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Robot operation system

### Links and sources

https://www.ros.org

**Comment by luizcarloscf** [comment] 2022-12-22 13:14
It seems to me that this issue is duplicated. https://github.com/devicons/devicon/issues/256
ROS icon is already in develop https://github.com/devicons/devicon/pull/1100

**Comment by Snailedlt** [comment] 2022-12-22 13:54
Duplicate of #256

**Closed by Snailedlt** 2022-12-22 13:54 UTC
Labels: request:icon
