### ISSUE TITLE
[ICON REQUEST]: Powershell

### ISSUE THREAD

**Issue by vmugutrao** [devicons/devicon#1145] opened 2022-04-18 15:24 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

powershell

### Links and sources

https://gist.github.com/Xainey/d5bde7d01dcbac51ac951810e94313aa#file-powershell-svg

**Comment by amacado** [comment] 2022-04-18 19:58
Duplicate of https://github.com/devicons/devicon/issues/364de

**Closed by amacado** 2022-04-18 19:58 UTC
Labels: request:icon
