### ISSUE TITLE
[ICON REQUEST]: VERCEL

### ISSUE THREAD

**Issue by tmsagarofficial** [devicons/devicon#1907] opened 2023-10-16 23:29 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

an American cloud platform as a service company. The company maintains the Next. js web development framework. Vercel's architecture is built around Jamstack, and deployments are handled through Git repositories.

### Links and sources

https://vercel.com

https://vercel.com/design/brands

### Additional information

I Would love to work on this issue too..

**Comment by Snailedlt** [comment] 2023-10-17 05:51
We don't accept icons of companies anymore, but since Vercel is also the name of one of their products this is valid

**Comment by Snailedlt** [comment] 2023-10-17 05:53
Turns out this is a duplicate of #1158 though, which is already merged to the `develop` branch

**Closed by Snailedlt** 2023-10-17 05:53 UTC
Labels: request:icon
