### ISSUE TITLE
[bug]: some svg's don't have color

### ISSUE THREAD

**Issue by gyasikn** [devicons/devicon#111] opened 2018-04-06 10:11 UTC
Multiple SVG's don't have color (React, Heroku, Visual Studio Code) to name a few...

Also React SVG is missing the dot in the center of the logo. (I realize this has been brought up before but it seems like nothing was done)

**Comment by iamclaytonray** [comment] 2018-12-16 16:18
Hey @gyasikn - I am unable to reproduce the missing dot in the React icon. Can you give me a way to reproduce this based on latest? I closed another issue pertaining to this but seems that a lot of people are dealing with this. Thanks!

As far as the colors go, I am going to go ahead and tag this as a bug and throw it into the 3.0 Project for the next release.

**Comment by Mr-Antivirus** [comment] 2019-12-29 04:15
From my observation, it's because there is a lack of css rules for that SVG. For instance, if you go to the 2.0 site and copy the code for "Twitter", the SVG will display in black because there is no CSS style for "cls-1". However, if you go to the actual repo file for Twitter and copy that SVG code, it has/defines the "cls-1" rule globally. So any other SVGs that use "cls-1" will instantly have that color now.

**Comment by Thomas-Boi** [comment] 2020-12-15 06:41
Hello there,

I am reasonably sure that all of these issues have been fixed. I have been unable to find svgs that lack colors so I'll be closing this issue for now. If anyone spot anything new, please let us know.

Cheers,

**Closed by Thomas-Boi** 2020-12-15 06:41 UTC
Labels: bug
