### ISSUE TITLE
Icon request: Unity

### ISSUE THREAD

**Issue by AhmedElTabarani** [devicons/devicon#631] opened 2021-05-25 18:06 UTC
### About the icon
Unity is a game engine, so it is within the domain of programmers and developers

### Links

https://commons.wikimedia.org/wiki/File:Unity_Technologies_logo.svg

**Comment by Thomas-Boi** [comment] 2021-05-27 04:13
I'll be closing this issue since it's a duplicate of #345.

**Closed by Thomas-Boi** 2021-05-27 04:13 UTC
Labels: request:icon
