### ISSUE TITLE
[ICON REQUEST]: GameMaker

### ISSUE THREAD

**Issue by BrantLauro** [devicons/devicon#1196] opened 2022-05-26 16:21 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

GameMaker is a great game engine for 2d games

### Links and sources

https://gamemaker.io/en
https://coal.gamemaker.io/sites/5d75794b3c84c70006700381/theme/images/svg/logomark.svg?1653389763
![image](https://user-images.githubusercontent.com/60024796/170530530-b17fc2f4-91ad-4b2b-ad58-d6d4b3ed9aac.png)

**Comment by Panquesito7** [comment] 2022-05-26 17:53
Duplicate of #633.

**Closed by Panquesito7** 2022-05-26 17:53 UTC
Labels: request:icon
