### ISSUE TITLE
[ICON REQUEST]: R programming language

### ISSUE THREAD

**Issue by msamanthaf** [devicons/devicon#1847] opened 2023-07-31 17:43 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Popular language for statistical computing, link:https://www.r-project.org/

### Links and sources

https://commons.wikimedia.org/wiki/File:R_logo.svg#/media/File:R_logo.svg

**Comment by Snailedlt** [comment] 2023-07-31 19:40
duplicate of #410 which is closed

**Closed by Snailedlt** 2023-07-31 19:40 UTC
Labels: request:icon
