### ISSUE TITLE
[ICON REQUEST]: <AWS>

### ISSUE THREAD

**Issue by Saha-7** [devicons/devicon#1854] opened 2023-08-22 08:30 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

AWS

### Links and sources

https://aws.amazon.com/free/?trk=16847e0c-46fb-467d-91ee-6e259e339665&sc_channel=ps&s_kwcid=AL!4422!10!72086958325164!72087482393523&ef_id=dc0e4d7b081b11645b1c299f79f74d80:G:s&all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all

### Additional information

Need an AWS icon.

**Comment by Snailedlt** [comment] 2023-08-22 12:15
Duplicate of #1204

**Closed by Snailedlt** 2023-08-22 12:15 UTC
Labels: request:icon
