### ISSUE TITLE
[ICON REQUEST]: Axios

### ISSUE THREAD

**Issue by mmh4all** [devicons/devicon#1155] opened 2022-04-25 13:05 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Popular Technology for xml http requests

### Links and sources

Official website
https://axios-http.com/docs/intro

Github link:
https://github.com/axios/axios

**Comment by amacado** [comment] 2022-04-25 13:25
Duplicate of #1056, already `in-develop` branch

**Closed by amacado** 2022-04-25 13:25 UTC
Labels: request:icon, duplicate
