### ISSUE TITLE
Icon request: Styled Components

### ISSUE THREAD

**Issue by MogLuiz** [devicons/devicon#870] opened 2021-09-29 14:17 UTC
### About the icon

styled-components is a library for React and React Native that allows you to use component-level styles in your application. They are written in a mixture of JavaScript and CSS.

### Links and sources

documentation : https://styled-components.com/

**Comment by Snailedlt** [comment] 2022-10-08 23:09
Duplicate of #332

**Closed by Snailedlt** 2022-10-08 23:09 UTC
Labels: request:icon
