### ISSUE TITLE
[ICON REQUEST]: <icon name>

### ISSUE THREAD

**Issue by psturm51** [devicons/devicon#1853] opened 2023-08-19 21:56 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Assembly and WebAssembly Icons

### Links and sources

There isn't really an icon for ASM but WebASM should have one.

### Additional information

Please

**Comment by Snailedlt** [comment] 2023-08-22 12:14
duplicate of #367

**Closed by Snailedlt** 2023-08-22 12:14 UTC
Labels: request:icon
