### ISSUE TITLE
[ICON REQUEST]: Netlify

### ISSUE THREAD

**Issue by RalphK66** [devicons/devicon#1159] opened 2022-04-26 06:47 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Extremely popular

### Links and sources

[netlify](https://www.netlify.com/)

**Comment by BenSouchet** [comment] 2022-07-27 12:11
@Snailedlt Duplicate of #854

**Comment by Snailedlt** [comment] 2022-07-27 13:22
@RalphK66 As mentioned above, this is a duplicate. Please go over to the other issue and vote for it instead :)

**Closed by Snailedlt** 2022-07-27 13:22 UTC
Labels: request:icon, duplicate
