### ISSUE TITLE
[ICON REQUEST]: <scikit-learn>

### ISSUE THREAD

**Issue by danaikorre** [devicons/devicon#1676] opened 2023-02-14 17:24 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Machine Learning in Python

### Links and sources

https://scikit-learn.org/stable/

### Additional information

It would be great to have more data science icons.

**Comment by Panquesito7** [comment] 2023-02-14 18:57
Duplicate of #1032.

**Comment by lauxpaux** [comment] 2023-06-07 21:15
Came here to request the same icon

**Closed** 2023-06-10 02:05 UTC
Labels: request:icon, duplicate
