### ISSUE TITLE
[ICON REQUEST]: <icon name>

### ISSUE THREAD

**Issue by abhishekvermaa10** [devicons/devicon#1852] opened 2023-08-19 09:49 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Maven is widely used in java projects and hence its icon should be available.

### Links and sources

Maven logo can be checked from https://maven.apache.org/ .

**Comment by Snailedlt** [comment] 2023-08-22 12:13
Maven is already in the develop branch

duplicate of #45

**Closed by Snailedlt** 2023-08-22 12:13 UTC
Labels: request:icon
