### ISSUE TITLE
[BUG] Svelte Wordmark icon is too small

### ISSUE THREAD

**Issue by grandslammer** [devicons/devicon#1213] opened 2022-06-15 15:22 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

See screenshots below...

React, Svelte (non-wordmark version), and Vue logos are provided for comparison.

The actual image is the correct size, but the icon itself within the image does not go to the edges of the image file (see 2nd screenshot)

![image](https://user-images.githubusercontent.com/18541062/173863776-1a2bffec-172e-4f54-8398-04dba1cefbf9.png)

![image](https://user-images.githubusercontent.com/18541062/173863908-38f74fd7-fd5f-4f2c-93bf-f136307ae07c.png)

### Possible fixes or solutions

Expand the Svelte wordmark logo so that the logo itself takes up the full available space within the image file, thus making it appear the same size as other logos.

**Comment by amacado** [comment] 2022-06-15 16:34
Duplicate of https://github.com/devicons/devicon/issues/1188

**Closed by amacado** 2022-06-15 16:34 UTC
Labels: bug
