### ISSUE TITLE
Bug Report: svg file of "vuestorefront" not exist.

### ISSUE THREAD

**Issue by mztnnrt** [devicons/devicon#693] opened 2021-06-24 11:35 UTC
`vuestorefront` SVG is not exist, but `devicons.json` is written about it

<img width="2160" alt="スクリーンショット 2021-06-24 20 30 24" src="https://user-images.githubusercontent.com/23626334/123255686-1a827780-d52b-11eb-81eb-16ee314d874f.png">

https://github.com/devicons/devicon/blob/9f4f5cdb393299a81125eb5127929ea7bfe42889/devicon.json#L3822-L3837

In fact, svg type `original` and `plain` is not exist 🙌

**Comment by amacado** [comment] 2021-06-24 14:52
It's actually not a bug by devicon, but a limitation by our used CDN (jsdelivr.net).
https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuestorefront/vuestorefront-original.svg
```
Package size exceeded the configured limit of 50 MB.
```

Other projects have this problem too, see https://github.com/jsdelivr/jsdelivr/issues/18177

Altough I have no idea why it's reporting this limit when accessing the vuestorefront icon (since it's only a few KB) there's probably not much we can do about. Maybe contacting jsdelivr?

**Comment by Thomas-Boi** [comment] 2021-06-26 05:15
Maybe we can fall back to another CDN or using the GitHub link when this happens instead? Here's a response from JSDelivr

> Package size exceeded the configured limit of 50 MB. Try https://github.com/devicons/devicon/tree/v2.12.0/icons/vuestorefront/vuestorefront-original.svg instead.

 => we can regexp this to find the url and load the icon that way.  It'll be better if JSDelivr can fix this but I think this is a decent fix

**Comment by Thomas-Boi** [comment] 2021-06-26 05:18
Just tested the 'fallback' link and it didn't work:
https://github.com/devicons/devicon/tree/v2.12.0/icons/vuestorefront/vuestorefront-original.svg 

This link work though:
https://github.com/devicons/devicon/blob/v2.12.0/icons/vueStorefront/vuestorefront-original.svg

I dig around and find this:
![image](https://user-images.githubusercontent.com/43018778/123502693-25104000-d603-11eb-87a5-cee61bc7eb11.png)

Perhaps the error message was wrong? The issue might have been with the folder path name all this time.

**Comment by Panquesito7** [comment] 2021-08-06 16:45
I think this is fixed now.

**Closed by Panquesito7** 2021-08-06 16:45 UTC
Labels: bug
