### ISSUE TITLE
Icon request: Visual Basic

### ISSUE THREAD

**Issue by cmcodes1** [devicons/devicon#213] opened 2020-05-29 00:51 UTC

**Comment by BenSouchet** [comment] 2022-01-15 14:28
Duplicate of https://github.com/devicons/devicon/issues/184 and https://github.com/devicons/devicon/issues/910
@Thomas-Boi

**Comment by Thomas-Boi** [comment] 2022-01-15 18:27
Please refer to #910 since it contains more details.

**Closed by Thomas-Boi** 2022-01-15 18:27 UTC
Labels: request:icon
