### ISSUE TITLE
[ICON REQUEST]: Apache Airflow

### ISSUE THREAD

**Issue by firqaaa** [devicons/devicon#1374] opened 2022-09-04 17:55 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

It is necessary tool for Data Engineer / ML Engineer

### Links and sources

https://airflow.apache.org

**Comment by weh** [comment] 2022-10-14 13:57
Icon is already in development
- PR: https://github.com/devicons/devicon/pull/1412
- Issue: https://github.com/devicons/devicon/issues/1163

**Comment by Snailedlt** [comment] 2022-10-19 13:49
Duplicate of #1163

**Closed by Snailedlt** 2022-10-19 13:49 UTC
Labels: request:icon, in-develop
