### ISSUE TITLE
[ICON REQUEST]: FaunaDB

### ISSUE THREAD

**Issue by AbdelrahmanDwedar** [devicons/devicon#1262] opened 2022-07-10 17:41 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Fauna is a database that is used wildly these days and I have heard a lot about it and how it uses a great new way of saving data. But I was confused when I didn't find it on Devicon at all.

### Links and sources

- [about](https://fauna.com/about)
I didn't find a good equality picture or SVG of their icon.

**Comment by AbdelrahmanDwedar** [comment] 2022-07-12 02:22
## Update:  
I found a higher equality png picture here:  
[https://dbdb.io/media/logos/fauna2020.png](https://dbdb.io/media/logos/fauna2020.png)

But it's added along the name, so I tried to cut it like so:  
![fauna logo](https://user-images.githubusercontent.com/67812625/178394648-72bf2d52-2bc0-42f3-beea-95a3fd17486c.png)

**Comment by Snailedlt** [comment] 2022-10-08 23:37
Duplicate of #769

**Closed by Snailedlt** 2022-10-08 23:37 UTC
Labels: request:icon, in-develop
