### ISSUE TITLE
[FEATURE REQUEST] GitHub Mark logo

### ISSUE THREAD

**Issue by ghost** [devicons/devicon#992] opened 2021-12-29 03:42 UTC
### About the icon

GitHub Mark Light logo

### Links and sources

https://github.com/logos
![GitHub-Mark-Light-120px-plus](https://user-images.githubusercontent.com/96730029/147625303-aa09f307-6171-4b71-8bf3-aeb857a93bd3.png)
at [devicon/icons/github/](https://github.com/devicons/devicon/tree/master/icons/github)

**Comment by kilian-paquier** [comment] 2022-07-17 13:44
Related to https://github.com/devicons/devicon/issues/977 cause it's the same icon as those registered today with inverted colors.

**Comment by lunatic-fox** [comment] 2022-11-03 17:20
I agree with @kilianpaquier. Maybe #1383 solves it.

**Comment by Snailedlt** [comment] 2023-01-12 13:39
duplicate of #977

**Closed by Snailedlt** 2023-01-12 13:39 UTC
Labels: request:icon, awaiting triage
