### ISSUE TITLE
[ICON REQUEST]: Lumen from Laravel

### ISSUE THREAD

**Issue by alerafart** [devicons/devicon#1272] opened 2022-07-16 18:21 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Laravel's micro framework

### Links and sources

Oficcial Lumen website
https://lumen.laravel.com/docs/9.x

Svg ressource logo
https://worldvectorlogo.com/logo/lumen-1

### Additional information

thanks

**Comment by Snailedlt** [comment] 2022-07-25 21:36
duplicate of #133

**Closed by Snailedlt** 2022-07-25 21:36 UTC
Labels: request:icon, duplicate
