### ISSUE TITLE
Python SVG Icon not work

### ISSUE THREAD

**Issue by KevinMalo** [devicons/devicon#93] opened 2017-12-08 16:11 UTC
Hi, the icons SVG of Python not Work. Its need the Path Fill.

**Comment by Kartstig** [comment] 2018-02-16 14:26
I have gotten the Python icon to work, but it doesn't release certain backgrounds, casing other subsequent icons to be colored yellow. I'm referring to:

https://github.com/konpa/devicon/blob/master/icons/python/python-original-wordmark.svg

**Comment by Altijd-youri** [comment] 2019-10-29 21:11
I added the path-fill with the correct Python logo colors to my svg code. Now it shows correctly, I think.

```
<svg viewBox="0 0 128 128">
              <path fill="#306998" d="M63.391 1.988c-4.222.02-8.252.379-11.8 1.007-10.45 1.846-12.346 5.71-12.346 12.837v9.411h24.693v3.137h-33.961c-7.176 0-13.46 4.313-15.426 12.521-2.268 9.405-2.368 15.275 0 25.096 1.755 7.311 5.947 12.519 13.124 12.519h8.491v-11.282c0-8.151 7.051-15.34 15.426-15.34h24.665c6.866 0 12.346-5.654 12.346-12.548v-23.513c0-6.693-5.646-11.72-12.346-12.837-4.244-.706-8.645-1.027-12.866-1.008zm-13.354 7.569c2.55 0 4.634 2.117 4.634 4.721 0 2.593-2.083 4.69-4.634 4.69-2.56 0-4.633-2.097-4.633-4.69-.001-2.604 2.073-4.721 4.633-4.721z"></path>
              <path fill="#FFD845" d="M91.682 28.38v10.966c0 8.5-7.208 15.655-15.426 15.655h-24.665c-6.756 0-12.346 5.783-12.346 12.549v23.515c0 6.691 5.818 10.628 12.346 12.547 7.816 2.297 15.312 2.713 24.665 0 6.216-1.801 12.346-5.423 12.346-12.547v-9.412h-24.664v-3.138h37.012c7.176 0 9.852-5.005 12.348-12.519 2.578-7.735 2.467-15.174 0-25.096-1.774-7.145-5.161-12.521-12.348-12.521h-9.268zm-13.873 59.547c2.561 0 4.634 2.097 4.634 4.692 0 2.602-2.074 4.719-4.634 4.719-2.55 0-4.633-2.117-4.633-4.719 0-2.595 2.083-4.692 4.633-4.692z"></path>
              <path opacity=".444" fill="#646464" enable-background="new" d="M97.309 119.597c0 3.543-14.816 6.416-33.091 6.416-18.276 0-33.092-2.873-33.092-6.416 0-3.544 14.815-6.417 33.092-6.417 18.275 0 33.091 2.872 33.091 6.417z"></path>
            </svg> 
```

**Comment by Kartstig** [comment] 2021-01-06 17:48
@Altijd-youri can you confirm that #103 fixes your issue?

**Comment by Altijd-youri** [comment] 2021-01-06 19:24
I will have a look this week. I hope to get back to you before the weekend.

**Comment by Altijd-youri** [comment] 2021-01-08 19:08
@Kartstig I have had a look into it. #103 seems to be about the [Python-orignal-wordmark](https://github.com/devicons/devicon/blob/develop/icons/python/python-original-wordmark.svg). I'm not sure anymore about which icon my complaint from a year ago was. So it did a bunch of tests with the different icons and could not reproduce the problem.

- [python-original.svg (from #103)](https://github.com/devicons/devicon/pull/103/files#diff-ab850aa1ae0a2acf6e8ef97c0cfdcb648ba52b7614b5c287c9019c2f257f5ed8)
- [python-original.svg (Kartstig/devicon)](https://github.com/Kartstig/devicon/blob/update-python/icons/python/python-original.svg) - Shows correctly
- python-original.svg (my own tweak from a year ago) - This on should not be used, it has no gradient.

![Screenshot_2021-01-08)](https://user-images.githubusercontent.com/37577327/104054236-06e98b80-51ed-11eb-8a37-01aba7e2013c.png)
_Same order as listed above. I used a black background so I could see transparency. (Note the white color in the first one and the drop shadow on the other two._

**Comment by Kartstig** [comment] 2021-01-09 17:51
@Altijd-youri thanks for your thoroughness on such an old ticket!

**Comment by amacado** [comment] 2021-02-12 17:13
I just checked all python icons (font and svg versions) with the latest devicon v2.9.0. In my opinion they are looking good now (also checked the black background). I'm closing this ticket since it seems to be fixed now. Feel free to reopen it when I have overseen something.

**Closed by amacado** 2021-02-12 17:13 UTC
Labels: bug
