### ISSUE TITLE
Icon request: Unreal

### ISSUE THREAD

**Issue by AhmedElTabarani** [devicons/devicon#632] opened 2021-05-25 18:09 UTC
### About the icon
Unreal is a game engine, so it is within the domain of programmers and developers

### Links

https://commons.wikimedia.org/wiki/File:Unreal_Engine_Logo.svg

**Comment by Thomas-Boi** [comment] 2021-05-27 04:14
I'll be closing this issue since it's a duplicate of #346

**Closed by Thomas-Boi** 2021-05-27 04:14 UTC
Labels: request:icon
