### ISSUE TITLE
[ICON REQUEST]: Bun

### ISSUE THREAD

**Issue by tonie06** [devicons/devicon#1340] opened 2022-08-11 05:29 UTC
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Bun is a JS Runtime just like Deno and Node

### Links and sources

https://bun.sh/
https://github.com/oven-sh/bun

### Additional information

None

**Comment by BenSouchet** [comment] 2022-08-12 11:36
Duplicate of https://github.com/devicons/devicon/issues/1282
@Snailedlt This can be closed 🙂

**Closed** 2022-08-12 14:53 UTC
Labels: request:icon, duplicate
