### ISSUE TITLE
Icon request: MariaDB

### ISSUE THREAD

**Issue by carxl** [devicons/devicon#1031] opened 2022-01-30 17:37 UTC
### About the icon

MariaDB is an open source relational database

### Links and sources

Website: https://mariadb.org/

Resource for the icon: https://en.wikipedia.org/wiki/File:MariaDB_colour_logo.svg

### Additional information

Wikepedia info: https://en.wikipedia.org/wiki/MariaDB

**Comment by AbdelrahmanDwedar** [comment] 2022-07-12 02:39
And This is the one without the name if you want to:  
![MariaDB)](https://user-images.githubusercontent.com/67812625/178396669-86ea827e-4d3d-4c64-a457-fbff05971ca3.png)

**Comment by BenSouchet** [comment] 2022-07-26 14:17
Duplicate of #921 @Snailedlt

**Closed** 2022-07-26 15:38 UTC
Labels: request:icon, duplicate
